### ISSUE TITLE
Understanding binary tree traversal methods

### ISSUE THREAD

**Issue by marnigee** [marnigee/binary-tree#1]
https://github.com/marnigee/binary-tree/blob/f18a7d5d368bc8d3226d8b98301861868afd4f0e/lib/binary_search_tree.rb#L20-L26

I'm trying to understand how this method works.

Let's say we have this tree and we call the method with the root (Node 10):
```
       10
      /   \
     9    11
```
If I add this debugging code:
```
  def in_order(node = @root, &block)
    puts "*** start of method ***"
    puts "-node is nil" if node.nil?
    return if node.nil?

    puts "-before recursive call to node.left: node key: #{node.key}"
    in_order(node.left, &block)
    # yield(node)
    puts "-before recursive call to node.right: node key: #{node.key}"
    in_order(node.right, &block)
    puts "-after recursive call to node.right: node key: #{node.key}"
    puts "*** end of method ***"
```
I get this output from calling 

```
*** start of method ***
-before recursive call to node.left: node key: 10
*** start of method ***
-before recursive call to node.left: node key: 9
*** start of method ***
-node is nil
-before recursive call to node.right: node key: 9
*** start of method ***
-node is nil
-after recursive call to node.right: node key: 9
*** end of method ***
-before recursive call to node.right: node key: 10
*** start of method ***
-before recursive call to node.left: node key: 11
*** start of method ***
-node is nil
-before recursive call to node.right: node key: 11
*** start of method ***
-node is nil
-after recursive call to node.right: node key: 11
*** end of method ***
-after recursive call to node.right: node key: 10
*** end of method ***
```
It makes sense to me until after the first `*** end of method ***` -- after that, how does the method get called with Node 10? It's Node 9 at the end of the method, and I just don't follow how it gets called by Node 10. What am I missing here?

**Comment by raydelpino29** [comment]
I'm not completely sure what this method is supposed to do. As I understand it, `#in_order`'s return value will always be the result of calling it only on the right side of the tree (since the last line of the method is `in_order(`**node.right**`, &block) `).

As for why Node 10 gets called after `*** end of method ***` is logged, this has to do with the method stack. With methods that call themselves (recursion), the method will call itself before it's finished executing. When this happens, the subsequent method calls are pushed onto a stack. Long story short, Node 10 gets logged after Node 9 because we are traveling back up the stack of method calls. Here's what the first couple steps look like:

- First we call `#in_order` with Node 10. 
- Then, before the method has an opportunity to fully execute, it calls itself (`in_order(node.left`[**9**]`, &block)`), pushing another method call onto the stack. 
- This method call (`in_order(node.left`[**9**]`, &block)`) actually returns `nil`, since neither its left or right nodes exist. In other words, calling `in_order(node.left`[**nil**]`, &block)` and `in_order(node.right`[**nil**]`, &block)` will hit the base case (`return if node.nil? `) and allow the method to finish execution. This is where "**end of method**" is logged.
- Since the method finishes executing, we return back up the stack. where the `node == 10`. This is where "before recursive call to node.right: node key: 10" is logged.

**Comment by marnigee** [comment]
> Then, before the method has an opportunity to fully execute, it calls itself (in_order(node.left[9], &block)), pushing another method call onto the stack.

@raydelpino29: Thank you for the 💡moment -- "pushing another method call onto the stack" was the missing piece!

**Comment by raydelpino29** [comment]
You're welcome @marnigee! Glad I was able to help!
